name: 'Build and deploy ASP.NET Core app to Azure Web App: web-dimdim-valornull'

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: web-dimdim-valornull
  PROJECT_PATH: DimDim.Web/DimDim.Web.csproj
  PUBLISH_DIR: publish

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build in Release mode
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      - name: Publish the project
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o '${{ github.workspace }}/${{ env.PUBLISH_DIR }}'

      - name: Verify published files (debug)
        run: ls -R ${{ github.workspace }}/${{ env.PUBLISH_DIR }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: production
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_e5d418287ba54bbd9992e2256ad3f26e }}
          package: '${{ github.workspace }}/${{ env.PUBLISH_DIR }}'
